# Generated by Django 2.0.9 on 2018-10-25 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perris.Persona'),
        ),
    ]
