# Generated by Django 2.0.9 on 2018-10-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perris', '0002_perro_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='rut',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
    ]
